project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  page-navigation: true
  title: "Haven Hold The Phone"
  description: ""
  site-url: "https://havenholdthephone.com"
  
  repo-url: https://github.com/randyzwitch/havenholdthephone
  repo-actions: [edit, issue]

  navbar:
    background: "#A7D5E8"
    # left:
    #   - href: index.qmd
    #     text: Home
    #   - about.qmd

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#A7D5E8"

format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "style/fontawesome.html"

freeze: auto

editor: visual