---
title: "Mission Statement"
---

## Welcome to Haven Hold The Phone!


Our mission is to establish an inclusive, supportive and non-judgmental forum within our Wallingford-Swarthmore School District community where parents and caregivers can learn about and discuss the impact of smartphones and social media on our children. We, as a community, will partner together to effectuate changes in our community norms that will mitigate risks these technologies may pose to our children.


## Objectives


* **Community Learning** - Everyone deserves accurate information about the benefits and harms of introducing smartphones and social media to our children.  We will seek to identify credible sources who can help provide answers to questions on these topics that parents and caregivers may be afraid to ask. 

  We intend to explore ways to engage in community discussions, book clubs, and expert lectures on relevant topics, including the latest research, resources, and strategies for parents struggling with how to approach balanced tech use.  

* **Empowering Families** - There is power in numbers.  Community norms and fear of social isolation for our children can make family decisions about technology difficult to navigate. We aspire to reduce the social pressure for our children to have and use smartphones and social media by implementing a voluntary, local community pledge.  

  Through the pledge, families can commit, for one or more of their children, to delay introducing smartphones until high school and social media until 16 years old.  The goal of this pledge is to create community connection and assure families that they will not be alone if they choose to prolong a smartphone-free childhood for their child. 

* **Fostering Communication** - We have so much to learn from each other.  We aim to facilitate communication between neighbors who are facing similar questions about technology with their children, as well as with parents who have already been through technology challenges and decisions with older children and can share lessons learned.

* **Advocating for Change** - School policy can be part of the solution. We will explore opportunities to advocate for and support school policies that reflect our shared ambition of responsible and balanced technology use, and to partner with those already engaged in similar advocacy efforts.